sudo: false
language: go
go:
  - 1.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install: true
script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - env GO111MODULE=on go vet ./...
  - env GO111MODULE=on go test -v -cover -race ./...
