sudo: false
language: go
go:
  - 1.7
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get github.com/kardianos/govendor
  - govendor sync
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet clearbit
  - go test -v -cover -race ./...
