sudo: false
language: go
go:
  - 1.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get github.com/kardianos/govendor
  - cd clearbit && govendor sync
script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -cover -race ./...
